---
#################################################################################
# Copyright (c) 2020 WANdisco
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#   http://www.apache.org/licenses/LICENSE-2.0
#
#   Apache License, Version 2.0
#
################################################################################
#
# This docker-compose.yml file will bring up an Livedata Migrator server

version: "3.7"

services:
  debug:
    image: ubuntu
    command: ["tail", "-f", "/dev/null"]
    volumes:
      - logging-livedata-migrator:/debug/ldm
    networks:
      - fusion

  livedata-migrator:
    image: wandisco/livedata-migrator:1.4.7
    restart: unless-stopped
    hostname: livedata-migrator
    environment:
      - FS_ID=sandbox
      - HDFS_SOURCE_FS_HOST=sandbox-hdp-vanilla
      - HDFS_SOURCE_FS_PORT=8020
    networks:
      - fusion
    ports:
      - 18080:18080
      - 2222:2222
    volumes:
      - logging-livedata-migrator:/var/log/wandisco/
      - livedata-migrator-etc-wandisco:/etc/wandisco
      - livedata-migrator-db:/opt/wandisco/livedata-migrator

volumes:
  logging-livedata-migrator:
  livedata-migrator-etc-wandisco:
  livedata-migrator-db:
